### ISSUE TITLE
Index of system design topics

### ISSUE THREAD

**Issue by Allaman** [Allaman/system-design-primer#4]

**Comment by JacobK233811** [comment]
@Allaman It would be great if you worked on this issue next to help normalize the terms for the core concepts that @Clijsters, @dominikbraun, and I use as we go down the tree.

**Comment by Allaman** [comment]
you are right :+1:

**Comment by Allaman** [comment]
@JacobK233811 Done
Not easy because a) there is no German word or b) the German translation would be ugly

**Comment by JacobK233811** [comment]
Understood. Thanks for getting this done in advance and I'll use the convention set here moving forward
